//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Tuya.Pagos.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GenericValuesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GenericValuesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Tuya.Pagos.Common.Resources.GenericValuesResource", typeof(GenericValuesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        public static string applicationJson {
            get {
                return ResourceManager.GetString("applicationJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string authorization {
            get {
                return ResourceManager.GetString("authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo invalido.
        /// </summary>
        public static string resultModelMsg {
            get {
                return ResourceManager.GetString("resultModelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocp-Apim-Subscription-Key.
        /// </summary>
        public static string subscriptionKey {
            get {
                return ResourceManager.GetString("subscriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test@tuya.com.co.
        /// </summary>
        public static string swContactEmail {
            get {
                return ResourceManager.GetString("swContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        public static string swContactName {
            get {
                return ResourceManager.GetString("swContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REST Service encargado de realizar operaciones de Pago.
        /// </summary>
        public static string swDescription {
            get {
                return ResourceManager.GetString("swDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /swagger/v1/swagger.json.
        /// </summary>
        public static string swRelativePath {
            get {
                return ResourceManager.GetString("swRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Tuya - Digital Card Orquestation API.
        /// </summary>
        public static string swTitle {
            get {
                return ResourceManager.GetString("swTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1.
        /// </summary>
        public static string swVersion {
            get {
                return ResourceManager.GetString("swVersion", resourceCulture);
            }
        }
    }
}
